//go:build !ignore_autogenerated

/*
Copyright 2026 Monty P

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
*/

// Code generated by controller-gen. DO NOT EDIT.

package happyedge

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HappyEdgeArgs) DeepCopyInto(out *HappyEdgeArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ScrapeInterval = in.ScrapeInterval
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make(map[string]MetricConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make(map[string]map[string]MetricConfig, len(*in))
		for key, val := range *in {
			var outVal map[string]MetricConfig
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]MetricConfig, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.ClusterMetrics != nil {
		in, out := &in.ClusterMetrics, &out.ClusterMetrics
		*out = make(map[string]ClusterMetricConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HappyEdgeArgs.
func (in *HappyEdgeArgs) DeepCopy() *HappyEdgeArgs {
	if in == nil {
		return nil
	}
	out := new(HappyEdgeArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HappyEdgeArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
