//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 Monty P

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	config "github.com/montypx/happy-edge-scheduling-plugin/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterMetricConfig)(nil), (*config.ClusterMetricConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterMetricConfig_To_config_ClusterMetricConfig(a.(*ClusterMetricConfig), b.(*config.ClusterMetricConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ClusterMetricConfig)(nil), (*ClusterMetricConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ClusterMetricConfig_To_v1_ClusterMetricConfig(a.(*config.ClusterMetricConfig), b.(*ClusterMetricConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HappyEdgeArgs)(nil), (*config.HappyEdgeArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HappyEdgeArgs_To_config_HappyEdgeArgs(a.(*HappyEdgeArgs), b.(*config.HappyEdgeArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.HappyEdgeArgs)(nil), (*HappyEdgeArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_HappyEdgeArgs_To_v1_HappyEdgeArgs(a.(*config.HappyEdgeArgs), b.(*HappyEdgeArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricConfig)(nil), (*config.MetricConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MetricConfig_To_config_MetricConfig(a.(*MetricConfig), b.(*config.MetricConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.MetricConfig)(nil), (*MetricConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_MetricConfig_To_v1_MetricConfig(a.(*config.MetricConfig), b.(*MetricConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_ClusterMetricConfig_To_config_ClusterMetricConfig(in *ClusterMetricConfig, out *config.ClusterMetricConfig, s conversion.Scope) error {
	out.Query = in.Query
	out.Tolerance = in.Tolerance
	return nil
}

// Convert_v1_ClusterMetricConfig_To_config_ClusterMetricConfig is an autogenerated conversion function.
func Convert_v1_ClusterMetricConfig_To_config_ClusterMetricConfig(in *ClusterMetricConfig, out *config.ClusterMetricConfig, s conversion.Scope) error {
	return autoConvert_v1_ClusterMetricConfig_To_config_ClusterMetricConfig(in, out, s)
}

func autoConvert_config_ClusterMetricConfig_To_v1_ClusterMetricConfig(in *config.ClusterMetricConfig, out *ClusterMetricConfig, s conversion.Scope) error {
	out.Query = in.Query
	out.Tolerance = in.Tolerance
	return nil
}

// Convert_config_ClusterMetricConfig_To_v1_ClusterMetricConfig is an autogenerated conversion function.
func Convert_config_ClusterMetricConfig_To_v1_ClusterMetricConfig(in *config.ClusterMetricConfig, out *ClusterMetricConfig, s conversion.Scope) error {
	return autoConvert_config_ClusterMetricConfig_To_v1_ClusterMetricConfig(in, out, s)
}

func autoConvert_v1_HappyEdgeArgs_To_config_HappyEdgeArgs(in *HappyEdgeArgs, out *config.HappyEdgeArgs, s conversion.Scope) error {
	out.PrometheusURL = in.PrometheusURL
	out.ScrapeInterval = in.ScrapeInterval
	out.Metrics = *(*map[string]config.MetricConfig)(unsafe.Pointer(&in.Metrics))
	out.Groups = *(*map[string]map[string]config.MetricConfig)(unsafe.Pointer(&in.Groups))
	out.ClusterMetrics = *(*map[string]config.ClusterMetricConfig)(unsafe.Pointer(&in.ClusterMetrics))
	out.PostBindDelay = in.PostBindDelay
	return nil
}

// Convert_v1_HappyEdgeArgs_To_config_HappyEdgeArgs is an autogenerated conversion function.
func Convert_v1_HappyEdgeArgs_To_config_HappyEdgeArgs(in *HappyEdgeArgs, out *config.HappyEdgeArgs, s conversion.Scope) error {
	return autoConvert_v1_HappyEdgeArgs_To_config_HappyEdgeArgs(in, out, s)
}

func autoConvert_config_HappyEdgeArgs_To_v1_HappyEdgeArgs(in *config.HappyEdgeArgs, out *HappyEdgeArgs, s conversion.Scope) error {
	out.PrometheusURL = in.PrometheusURL
	out.ScrapeInterval = in.ScrapeInterval
	out.Metrics = *(*map[string]MetricConfig)(unsafe.Pointer(&in.Metrics))
	out.Groups = *(*map[string]map[string]MetricConfig)(unsafe.Pointer(&in.Groups))
	out.ClusterMetrics = *(*map[string]ClusterMetricConfig)(unsafe.Pointer(&in.ClusterMetrics))
	out.PostBindDelay = in.PostBindDelay
	return nil
}

// Convert_config_HappyEdgeArgs_To_v1_HappyEdgeArgs is an autogenerated conversion function.
func Convert_config_HappyEdgeArgs_To_v1_HappyEdgeArgs(in *config.HappyEdgeArgs, out *HappyEdgeArgs, s conversion.Scope) error {
	return autoConvert_config_HappyEdgeArgs_To_v1_HappyEdgeArgs(in, out, s)
}

func autoConvert_v1_MetricConfig_To_config_MetricConfig(in *MetricConfig, out *config.MetricConfig, s conversion.Scope) error {
	out.Query = in.Query
	out.Ideal = in.Ideal
	out.Worst = in.Worst
	out.Weight = in.Weight
	return nil
}

// Convert_v1_MetricConfig_To_config_MetricConfig is an autogenerated conversion function.
func Convert_v1_MetricConfig_To_config_MetricConfig(in *MetricConfig, out *config.MetricConfig, s conversion.Scope) error {
	return autoConvert_v1_MetricConfig_To_config_MetricConfig(in, out, s)
}

func autoConvert_config_MetricConfig_To_v1_MetricConfig(in *config.MetricConfig, out *MetricConfig, s conversion.Scope) error {
	out.Query = in.Query
	out.Ideal = in.Ideal
	out.Worst = in.Worst
	out.Weight = in.Weight
	return nil
}

// Convert_config_MetricConfig_To_v1_MetricConfig is an autogenerated conversion function.
func Convert_config_MetricConfig_To_v1_MetricConfig(in *config.MetricConfig, out *MetricConfig, s conversion.Scope) error {
	return autoConvert_config_MetricConfig_To_v1_MetricConfig(in, out, s)
}
